[preface]
= Introduction

This project began when I ventured into creating a {PureBasic} version of the ARun interpreter as a fun-project, mostly as a mean to learn the inner-workings of ARun and its Amachine (see my {doc-pb} document).

But there were also practical motivations for doing so, for I always wanted to create an ALAN version of {Inform7}`'s {Skein} tool along with an ALAN visual debugger -- two projects which could benefit from PureBasic's cross-platform GUI components.

As the project evolved, I also started working on a binary structure definition of the **.a3c** file format for {HexEditorNeo}, the hex editor which I use in my daily work.
This definition allowed me to checked the expected data in any compiled adventure, allowing me to better understand where and how my hand-coded parser was going haywire.

In the meantime Hex Editor Neo added native support for {KaitaiStruct} definitions, which prompted me to start working on an **.a3c** definition for Kaitai Struct too.

So, ultimately, I decided to incorporate into the project these binary definitions I'm working on, along with my PureBasic port experiments, broadening the scope of this project -- the repository was eventually renamed from `alan-pb` to `arun-playground`, and this book from "`ARun PureBasic`" to "`ARun Clockwork`".
The project is now no longer restricted to the PureBasic language either, since I've decided to also explore other programming languages to experiment with implementing ARun ports.

Since these goals are still far from reach, for the time being this project will offer me a chance to document ARun's design and the ALAN storyfile format (neither of which are currently documented).


=== Methodology and Conventions

In the course of this book I'll try to describe the inner workings of ARun in a language agnostic way, in order to simplify creating an ALAN interpreter in any language.
At the same time, I shall provide references to the original C sources of ARun, including code excerpts, based on the assumption that to fully understand ARun it's necessary to study its source code.
Finally, since this document was created in relation to my PureBasic port of ARun, I shall also add PureBasic specific notes and code examples, when needed.

When discussing primitive scalar data types, I'll resort to Rust's types naming convention which provides a more immediate representation of the types in terms of their width/precision, signedness, etc. -- e.g. `i32` and `i64` represent signed integers of 32- and 64-bit width, respectively, whereas `u32` and `u64` represent their unsigned counterparts.
This approach should dispel any ambiguities about the C types (which are often subject to different architecture or compiler interpretations) and PureBasic's bizarre naming of its native types.


=== ARun {AlanVer}

All references to the upstream ARun code, and excerpts thereof, refer to ARun v{AlanVer}.
The upstream ARun v{AlanVer} sources can be viewed on GitHub at:

* https://github.com/alan-if/alan/tree/v{AlanVer}/interpreter[^]

This decision to stick with a specific version is motivated by the fact that I wanted to have a fixed codebase to work on, without having to deal with upstream code changes and their integration in the book.

Although this might be a limiting choice in the long run, I'm not expecting to switch to another ARun version until it reaches v3.0 stable release, or unless its source code undergoes major changes (which is fairly unlikely right now).

The aim of this book is to introduce the reader to the inner workings of ARun, its data structures, the Amachine, etc.; having learnt these, he/she should be able to easily work with the latest upstream source code, regardless of any new changes to it.


=== Useful References

Some external links to Issues, Discussions or other useful material on the topics of this books.

* {alan_48} -- ACD and Acode vs Text File
* {alan_49} -- Compiler Version in .a3c Storyfiles
